In [1]:
print('hello')

hello

Approach for scraping from dexscreener

- using Apify

https://apify.com/muhammetakkurtt/dexscreener-scraper

Hit "Run" and wait for a min. You'll then get top 100 trending tokens. Copy the link to the dataset/download it

In [2]:
import pandas as pd

In [8]:
dataset_id = "pDDPgMDNve6I966du"

In [10]:
url = f"https://api.apify.com/v2/datasets/{dataset_id}/items?clean=true"

In [15]:
df = pd.read_json(url)

In [16]:
df

,chainId,dexId,url,pairAddress,baseToken,quoteToken,priceNative,priceUsd,txns,volume,priceChange,fdv,marketCap,pairCreatedAt,info,liquidity,boosts,labels,moonshot
0,solana,pumpfun,https://dexscreener.com/solana/cepddjzovkfd8qt...,CEpdDJZoVkFd8qty2gui3oCx3GURuDuivTNVW9KQEyPS,{'address': 'G9sTp9mXkM8FyiEV4dM76XzMkdmDAkhg6...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 29645.36, 'h6': 29645.36, 'h1': 0, 'm5...","{'h6': 1193, 'h24': 1193}",6.168955e+04,6.168955e+04,1746205104000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,NaN,NaN,NaN
1,solana,pumpswap,https://dexscreener.com/solana/8qdz7ngk8mf53mt...,8qDZ7NGK8mf53MTzo2a5GjdQueu4wyhbn5AqhcFVST5R,{'address': 'Hxxmg1atgaEW6zPFLikiR8n923HzE3oX8...,{'address': 'So1111111111111111111111111111111...,3.452000e-06,0.000511,"{'m5': {'buys': 144, 'sells': 85}, 'h1': {'buy...","{'h24': 22618652.98, 'h6': 22618652.98, 'h1': ...","{'m5': -11.05, 'h1': -35.61, 'h6': 726, 'h24':...",5.112280e+05,5.112280e+05,1746204730000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 106195.8, 'base': 103899508, 'quote': ...",{'active': 10},NaN,NaN
2,solana,pumpfun,https://dexscreener.com/solana/6zzryi2mtese3ce...,6zzryi2mtESe3ceKVT7BZK5UjowHAAFw29bTA252mpvp,{'address': '4rjoKMxXay5NaVvFxdZWCQA71NnnTve6P...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 12802.47, 'h6': 12802.47, 'h1': 0, 'm5...","{'h6': 1360, 'h24': 1360}",6.157039e+04,6.157039e+04,1746202616000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,{'active': 5000},NaN,NaN
3,solana,pumpswap,https://dexscreener.com/solana/37iwfsqgntsafsh...,37iWFSqgnTSAfShoBTBzQghwsTtkWAZW3yVzgJWKn6iK,{'address': '38PgzpJYu2HkiYvV8qePFakB8tuobPdGm...,{'address': 'So1111111111111111111111111111111...,1.098000e-04,0.016270,"{'m5': {'buys': 68, 'sells': 30}, 'h1': {'buys...","{'h24': 25979335.53, 'h6': 9743405.21, 'h1': 1...","{'m5': -1.56, 'h1': 3.3, 'h6': -31.44, 'h24': ...",1.627143e+07,1.627143e+07,1746044748000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 804068.5, 'base': 24729371, 'quote': 2...",NaN,NaN,NaN
4,solana,pumpfun,https://dexscreener.com/solana/6kztwbctmaqxima...,6kZtWbcTMaqxiMavuN4aT2XcduDX38KJEYFCrvL6Pj1d,{'address': 'AFMyfmGLmZ7VGfqbQ3aUaHtNQnH3mE4T1...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 98316.27, 'h6': 0, 'h1': 0, 'm5': 0}",{'h24': 1277},6.178405e+04,6.178405e+04,1746185533000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,solana,raydium,https://dexscreener.com/solana/gdpdqqvbqzbsuel...,GdpdQqvBqzBsUEL97bW9ebtCtVKygjH72Tzid896XuHG,{'address': 'CdZuiJEgdwQVZBWZrd6MvYwZshsT5HvB6...,{'address': 'So1111111111111111111111111111111...,7.400000e-06,0.001096,"{'m5': {'buys': 1, 'sells': 1}, 'h1': {'buys':...","{'h24': 1178430.03, 'h6': 163478.67, 'h1': 309...","{'m5': 0.31, 'h1': 8.25, 'h6': 3.17, 'h24': -2...",1.096035e+06,1.096035e+06,1746123872000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 120336.59, 'base': 54896346, 'quote': ...",{'active': 100},[CPMM],NaN
89,solana,pumpswap,https://dexscreener.com/solana/7rmmys9xbs8uz6b...,7RmMys9XBS8uz6bvjSKcrHaC682HyyXGEpAjhfVYnFXT,{'address': '5cQtbxhPTVQJVKKiQazpmQpSZzEJaZ86F...,{'address': 'So1111111111111111111111111111111...,3.754000e-06,0.000556,"{'m5': {'buys': 2, 'sells': 1}, 'h1': {'buys':...","{'h24': 872813.93, 'h6': 282940.17, 'h1': 1596...","{'m5': -1.71, 'h1': 10.08, 'h6': 1.59, 'h24': ...",5.561120e+05,5.561120e+05,1745964987000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 91438.66, 'base': 82242173, 'quote': 3...",NaN,NaN,NaN
90,solana,raydium,https://dexscreener.com/solana/48exm5rhcahddh5...,48ExM5rHCahDdh5V1Liije5D2vwKVXB5rgGGnBbJ5biP,{'address': '2G4RMDbXu79f5Yff6fBjKgXknuGvrFCr7...,{'address': 'So1111111111111111111111111111111...,2.843000e-05,0.004210,"{'m5': {'buys': 2, 'sells': 3}, 'h1': {'buys':...","{'h24': 282019.78, 'h6': 93806.62, 'h1': 36202...","{'m5': -0.44, 'h1': -9.91, 'h6': 39.47, 'h24':...",4.210808e+06,4.210808e+06,1744998250000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 253265.33, 'base': 30073249, 'quote': ...",NaN,[CPMM],NaN
91,solana,raydium,https://dexscreener.com/solana/geacz94pw7egzsp...,GEacZ94pW7egZsPLgNWXrWBnA5qPTfbRUU5epdfjaLF2,{'address': 'Hg8bKz4mvs8KNj9zew1cEF9tDw1x2GViB...,{'address': 'So1111111111111111111111111111111...,1.230000e-02,1.820000,"{'m5': {'buys': 6, 'sells': 56}, 'h1': {'buys'...","{'h24': 26202744.65, 'h6': 5247471.49, 'h1': 7...","{'m5': 1.26, 'h1': 8.77, 'h6': 1.06, 'h24': 19...",1.167040e+09,1.167040e+09,1741187282000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 25173649.1, 'base': 7781983, 'quote': ...",NaN,[CLMM],NaN
92,solana,pumpswap,https://dexscreener.com/solana/3yf4sjyfwbdsjea...,3YF4SJYfWBdsjeA3Li2ZnnegCvHAyKTmyxg4vq8LL722,{'address': 'GLYUabrtoQ6Qz71ySPZypEKbmQahCbp56...,{'address': 'So1111111111111111111111111111111...,9.072000e-07,0.000134,"{'m5': {'buys': 5, 'sells': 2}, 'h1': {'buys':...","{'h24': 769431.47, 'h6': 177776.39, 'h1': 1423...","{'m5': 3.05, 'h1': 0.4, 'h6': -0.21, 'h24': 182}",1.343490e+05,1.343490e+05,1746094815000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 43102.87, 'base': 160071190, 'quote': ...",NaN,NaN,NaN

In [17]:
df.columns

Index(['chainId', 'dexId', 'url', 'pairAddress', 'baseToken', 'quoteToken',
       'priceNative', 'priceUsd', 'txns', 'volume', 'priceChange', 'fdv',
       'marketCap', 'pairCreatedAt', 'info', 'liquidity', 'boosts', 'labels',
       'moonshot'],
      dtype='object')

In [18]:
df.head()

,chainId,dexId,url,pairAddress,baseToken,quoteToken,priceNative,priceUsd,txns,volume,priceChange,fdv,marketCap,pairCreatedAt,info,liquidity,boosts,labels,moonshot
0,solana,pumpfun,https://dexscreener.com/solana/cepddjzovkfd8qt...,CEpdDJZoVkFd8qty2gui3oCx3GURuDuivTNVW9KQEyPS,{'address': 'G9sTp9mXkM8FyiEV4dM76XzMkdmDAkhg6...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 29645.36, 'h6': 29645.36, 'h1': 0, 'm5...","{'h6': 1193, 'h24': 1193}",61689.55,61689.55,1746205104000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,NaN,NaN,NaN
1,solana,pumpswap,https://dexscreener.com/solana/8qdz7ngk8mf53mt...,8qDZ7NGK8mf53MTzo2a5GjdQueu4wyhbn5AqhcFVST5R,{'address': 'Hxxmg1atgaEW6zPFLikiR8n923HzE3oX8...,{'address': 'So1111111111111111111111111111111...,3.452000e-06,0.000511,"{'m5': {'buys': 144, 'sells': 85}, 'h1': {'buy...","{'h24': 22618652.98, 'h6': 22618652.98, 'h1': ...","{'m5': -11.05, 'h1': -35.61, 'h6': 726, 'h24':...",511228.00,511228.00,1746204730000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 106195.8, 'base': 103899508, 'quote': ...",{'active': 10},NaN,NaN
2,solana,pumpfun,https://dexscreener.com/solana/6zzryi2mtese3ce...,6zzryi2mtESe3ceKVT7BZK5UjowHAAFw29bTA252mpvp,{'address': '4rjoKMxXay5NaVvFxdZWCQA71NnnTve6P...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 12802.47, 'h6': 12802.47, 'h1': 0, 'm5...","{'h6': 1360, 'h24': 1360}",61570.39,61570.39,1746202616000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,{'active': 5000},NaN,NaN
3,solana,pumpswap,https://dexscreener.com/solana/37iwfsqgntsafsh...,37iWFSqgnTSAfShoBTBzQghwsTtkWAZW3yVzgJWKn6iK,{'address': '38PgzpJYu2HkiYvV8qePFakB8tuobPdGm...,{'address': 'So1111111111111111111111111111111...,1.098000e-04,0.016270,"{'m5': {'buys': 68, 'sells': 30}, 'h1': {'buys...","{'h24': 25979335.53, 'h6': 9743405.21, 'h1': 1...","{'m5': -1.56, 'h1': 3.3, 'h6': -31.44, 'h24': ...",16271434.00,16271434.00,1746044748000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 804068.5, 'base': 24729371, 'quote': 2...",NaN,NaN,NaN
4,solana,pumpfun,https://dexscreener.com/solana/6kztwbctmaqxima...,6kZtWbcTMaqxiMavuN4aT2XcduDX38KJEYFCrvL6Pj1d,{'address': 'AFMyfmGLmZ7VGfqbQ3aUaHtNQnH3mE4T1...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 98316.27, 'h6': 0, 'h1': 0, 'm5': 0}",{'h24': 1277},61784.05,61784.05,1746185533000,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,NaN,NaN,NaN

In [20]:
# First, expand the nested dicts
df['liquidity_usd'] = df['liquidity'].apply(lambda x: x.get('usd') if isinstance(x, dict) else None)
df['volume_h24'] = df['volume'].apply(lambda x: x.get('h24') if isinstance(x, dict) else None)

# Now compute the ratios
df['liquidity_to_volume'] = df['liquidity_usd'] / df['volume_h24']
df['fdv_to_liquidity'] = df['fdv'] / df['liquidity_usd']

In [21]:
df

,chainId,dexId,url,pairAddress,baseToken,quoteToken,priceNative,priceUsd,txns,volume,...,info,liquidity,boosts,labels,moonshot,age_hours,liquidity_usd,volume_h24,liquidity_to_volume,fdv_to_liquidity
0,solana,pumpfun,https://dexscreener.com/solana/cepddjzovkfd8qt...,CEpdDJZoVkFd8qty2gui3oCx3GURuDuivTNVW9KQEyPS,{'address': 'G9sTp9mXkM8FyiEV4dM76XzMkdmDAkhg6...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 29645.36, 'h6': 29645.36, 'h1': 0, 'm5...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,NaN,NaN,NaN,3.892430,NaN,29645.36,NaN,NaN
1,solana,pumpswap,https://dexscreener.com/solana/8qdz7ngk8mf53mt...,8qDZ7NGK8mf53MTzo2a5GjdQueu4wyhbn5AqhcFVST5R,{'address': 'Hxxmg1atgaEW6zPFLikiR8n923HzE3oX8...,{'address': 'So1111111111111111111111111111111...,3.452000e-06,0.000511,"{'m5': {'buys': 144, 'sells': 85}, 'h1': {'buy...","{'h24': 22618652.98, 'h6': 22618652.98, 'h1': ...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 106195.8, 'base': 103899508, 'quote': ...",{'active': 10},NaN,NaN,3.996319,106195.80,22618652.98,0.004695,4.814013
2,solana,pumpfun,https://dexscreener.com/solana/6zzryi2mtese3ce...,6zzryi2mtESe3ceKVT7BZK5UjowHAAFw29bTA252mpvp,{'address': '4rjoKMxXay5NaVvFxdZWCQA71NnnTve6P...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 12802.47, 'h6': 12802.47, 'h1': 0, 'm5...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,{'active': 5000},NaN,NaN,4.583541,NaN,12802.47,NaN,NaN
3,solana,pumpswap,https://dexscreener.com/solana/37iwfsqgntsafsh...,37iWFSqgnTSAfShoBTBzQghwsTtkWAZW3yVzgJWKn6iK,{'address': '38PgzpJYu2HkiYvV8qePFakB8tuobPdGm...,{'address': 'So1111111111111111111111111111111...,1.098000e-04,0.016270,"{'m5': {'buys': 68, 'sells': 30}, 'h1': {'buys...","{'h24': 25979335.53, 'h6': 9743405.21, 'h1': 1...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 804068.5, 'base': 24729371, 'quote': 2...",NaN,NaN,NaN,48.435763,804068.50,25979335.53,0.030950,20.236378
4,solana,pumpfun,https://dexscreener.com/solana/6kztwbctmaqxima...,6kZtWbcTMaqxiMavuN4aT2XcduDX38KJEYFCrvL6Pj1d,{'address': 'AFMyfmGLmZ7VGfqbQ3aUaHtNQnH3mE4T1...,{'address': 'So1111111111111111111111111111111...,4.108000e-07,0.000062,"{'m5': {'buys': 0, 'sells': 0}, 'h1': {'buys':...","{'h24': 98316.27, 'h6': 0, 'h1': 0, 'm5': 0}",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,NaN,NaN,NaN,NaN,9.328819,NaN,98316.27,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,solana,raydium,https://dexscreener.com/solana/gdpdqqvbqzbsuel...,GdpdQqvBqzBsUEL97bW9ebtCtVKygjH72Tzid896XuHG,{'address': 'CdZuiJEgdwQVZBWZrd6MvYwZshsT5HvB6...,{'address': 'So1111111111111111111111111111111...,7.400000e-06,0.001096,"{'m5': {'buys': 1, 'sells': 1}, 'h1': {'buys':...","{'h24': 1178430.03, 'h6': 163478.67, 'h1': 309...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 120336.59, 'base': 54896346, 'quote': ...",{'active': 100},[CPMM],NaN,26.456874,120336.59,1178430.03,0.102116,9.108078
89,solana,pumpswap,https://dexscreener.com/solana/7rmmys9xbs8uz6b...,7RmMys9XBS8uz6bvjSKcrHaC682HyyXGEpAjhfVYnFXT,{'address': '5cQtbxhPTVQJVKKiQazpmQpSZzEJaZ86F...,{'address': 'So1111111111111111111111111111111...,3.754000e-06,0.000556,"{'m5': {'buys': 2, 'sells': 1}, 'h1': {'buys':...","{'h24': 872813.93, 'h6': 282940.17, 'h1': 1596...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 91438.66, 'base': 82242173, 'quote': 3...",NaN,NaN,NaN,70.591597,91438.66,872813.93,0.104763,6.081804
90,solana,raydium,https://dexscreener.com/solana/48exm5rhcahddh5...,48ExM5rHCahDdh5V1Liije5D2vwKVXB5rgGGnBbJ5biP,{'address': '2G4RMDbXu79f5Yff6fBjKgXknuGvrFCr7...,{'address': 'So1111111111111111111111111111111...,2.843000e-05,0.004210,"{'m5': {'buys': 2, 'sells': 3}, 'h1': {'buys':...","{'h24': 282019.78, 'h6': 93806.62, 'h1': 36202...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 253265.33, 'base': 30073249, 'quote': ...",NaN,[CPMM],NaN,339.129652,253265.33,282019.78,0.898041,16.626074
91,solana,raydium,https://dexscreener.com/solana/geacz94pw7egzsp...,GEacZ94pW7egZsPLgNWXrWBnA5qPTfbRUU5epdfjaLF2,{'address': 'Hg8bKz4mvs8KNj9zew1cEF9tDw1x2GViB...,{'address': 'So1111111111111111111111111111111...,1.230000e-02,1.820000,"{'m5': {'buys': 6, 'sells': 56}, 'h1': {'buys'...","{'h24': 26202744.65, 'h6': 5247471.49, 'h1': 7...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 25173649.1, 'base': 7781983, 'quote': ...",NaN,[CLMM],NaN,1397.731874,25173649.10,26202744.65,0.960726,46.359568
92,solana,pumpswap,https://dexscreener.com/solana/3yf4sjyfwbdsjea...,3YF4SJYfWBdsjeA3Li2ZnnegCvHAyKTmyxg4vq8LL722,{'address': 'GLYUabrtoQ6Qz71ySPZypEKbmQahCbp56...,{'address': 'So1111111111111111111111111111111...,9.072000e-07,0.000134,"{'m5': {'buys': 5, 'sells': 2}, 'h1': {'buys':...","{'h24': 769431.47, 'h6': 177776.39, 'h1': 1423...",...,{'imageUrl': 'https://dd.dexscreener.com/ds-da...,"{'usd': 43102.87, 'base': 160071190, 'quote': ...",NaN,NaN,NaN,34.528263,43102.87,769431.47,0.056019,3.116939